name: 'Dotnet Core CI + Octopus Deploy Docker Container'
description: 'GitHub Action to deploy a DotNet Framework solution Octopus as a Docker Container'
inputs:
  CREATE_RELEASE:  
    description: 'If true, this build will be sent to Octopus, otherwise it will only be tested'
    required: true
  OCTOPUS_URL:  
    description: 'Octopus url'
    required: false
  OCTOPUS_APIKEY:  
    description: 'Api Key'
    required: false
  MS_TEAMS_WEBHOOK:  
    description: 'If set, A MS Teams notification will be sent to this webhook'
    required: false
  DBUP_PROJECT:
    description: 'Name of DbUp project if required'
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'package'  
  color: 'blue'