name: 'Dotnet Core CI + Octopus Deploy Docker Container'
description: 'GitHub Action to deploy a DotNet Framework solution Octopus as a Docker Container'
inputs:
  CREATE_RELEASE:  
    description: 'If true, this build will be sent to Octopus, otherwise it will only be tested'
    required: true
  OCTOPUS_URL:  
    description: 'Octopus url'
    required: false
  OCTOPUS_APIKEY:  
    description: 'Api Key'
    required: false
  MS_TEAMS_WEBHOOK:  
    description: 'If set, A MS Teams notification will be sent to this webhook'
    required: false
  DBUP_PROJECT:
    description: 'Name of DbUp project if required'
    required: false
  DOCKER_PROJECT:
    description: 'Name of Docker Project to push to registry'
    required: true
  REGISTRY_HOST:
    description: 'Name of Docker registry host to push to'
    required: true
  REGISTRY_USERNAME:
    description: 'Username for docker registry'
    required: true
  REGISTRY_PASSWORD:
    description: 'Password for docker registry user'
    required: true
  TARGET_PLATFORM:
    description: 'Specify dotnet platform for dbup project (defaults to win-x64)'
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'package'  
  color: 'blue'